version: "3.3"

services:
  db:
    image: postgres
    restart: always
    container_name: db
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: vencilanding
    ports:
      - 54328:5432

  app:
    build: .
    restart: always
    container_name: app
    # command: bash ./start_prod_server.sh
    ports:
      - 127.0.0.1:5000:5000
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app
    environment:
      - FLASK_APP=wsgi:app
      - FLASK_ENV=production
      - FLASK_DEBUG=0

volumes:
  db_data:
